#!/system/bin/sh
mount -o remount,noauto_da_alloc,nosuid,nodev,noatime,nodiratime /data /data

# added per request on XDA Trinity Thread
# Thanks brainmaster, Kurupt1, Maximilian Mary
# Thanks simms22 - 666

# Define the memory thresholds at which the above process classes will
# be killed.  These numbers are in pages (4k).
#    setprop ro.FOREGROUND_APP_MEM 1536
#    setprop ro.VISIBLE_APP_MEM 2048
#    setprop ro.PERCEPTIBLE_APP_MEM 4096
#    setprop ro.HEAVY_WEIGHT_APP_MEM 4096
#    setprop ro.SECONDARY_SERVER_MEM 15360
#    setprop ro.BACKUP_APP_MEM 15360
#    setprop ro.HOME_APP_MEM 15360
#    setprop ro.HIDDEN_APP_MEM 17920
#    setprop ro.EMPTY_APP_MEM 20480

# readding old minfree tweaks and other stuff the ramdisk ruins unless i fix it
# this set must match the set above
echo "1536,2304,4096,17920,19456,41472" > /sys/module/lowmemorykiller/parameters/minfree

    # Tweak background writeout
echo 500 > /proc/sys/vm/dirty_writeback_centicsecs
echo 50 > /proc/sys/vm/dirty_expire_centisecs
echo 4 > write /proc/sys/vm/dirty_ratio
echo 2 > write /proc/sys/vm/dirty_background_ratio

